routes:
  /sitemap/:
      template: sitemap
      content_type: text/xml

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: tag:-daily-orthodox

taxonomies:
  tag: /t/{slug}/
  author: /author/{slug}/
